version: '3.8'

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-container
    ports:
      - "8777:8080" # Веб-интерфейс Jenkins
      - "50050:50000"  # Связь между Jenkins master и agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

volumes:
  jenkins_home: