version: "3.8"

services:
  fast-api-service:
    container_name: fast-api-container
    image: fast-api
    build: ./
    ports:
      - "8887:8887"
    env_file:
      - .env.prod
    depends_on:
      - alembic_runner
    command: ["python3.12", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8887"]
    volumes:
      - ./:/tutoring_service
    restart: always

  alembic_runner:
    container_name: alembic-container
    image: fast-api
    build: .
    env_file:
      - .env.prod
    command: ["/bin/sh", "./docker/alembic.sh"]
    volumes:
      - ./migrations/versions:/tutoring_service/migrations/versions


