version: "3.8"

services:
  fast-api:
    container_name: fast-api-container
    image: fast-api
    build: ./
    ports:
      - "8887:8887"
    env_file:
      - .env.prod
    depends_on:
      - alembic_runner
    command: ["python3.12", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8887"]
    volumes:
      - ./:/tutoring_service
    restart: always

  alembic_runner:
    container_name: alembic-container
    image: fast-api
    build: .
    env_file:
      - .env.prod
    command: ["/bin/sh", "./docker/alembic.sh"]
    volumes:
      - ./:/tutoring_service

  postgres_service:
    container_name: postgres-container
    image: postgres
    env_file:
      - .env.prod
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5435:${DB_PORT}"
    volumes:
      - .postgres:/var/lib/postgres/data
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # Добавляем инициализационный скрипт
    restart: always

  jenkins:
    build: ./jenkins
    container_name: jenkins-container
    ports:
      - "8777:8080" # Веб-интерфейс Jenkins
      - "50050:50000"  # Связь между Jenkins master и agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

volumes:
  jenkins_home:
