version: "3.8"

services:
  fast-api:
    container_name: fast-api-container
    build: ./
    depends_on:
      - postgres_service
    command: 'python3.12 main.py'
    volumes:
      - ./:/tutoring_service_data
    restart: always
    env_file:
      - .env-prod
    ports:
      - ${SERVER_PORT}:8000

  postgres_service:
    container_name: postgres-container
    image: postgres
    env_file:
      - .env-prod
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always
