version: "3.8"

networks:
  services_network:
    external: true

services:
  postgres_service:
    container_name: postgres-container
    image: postgres
    networks:
      - services_network
    env_file:
      - .env.prod
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5435:${DB_PORT}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./docker/init_db.sh:/docker-entrypoint-initdb.d/init-db.sh  # Добавляем инициализационный скрипт
    restart: always

  jenkins:
    build: ./jenkins
    container_name: jenkins-container
    networks:
      - services_network
    ports:
      - "8777:8080" # Веб-интерфейс Jenkins
      - "50050:50000"  # Связь между Jenkins master и agents
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

volumes:
  jenkins_home: