version: '3.8'

services:
  postgres_service:
    container_name: postgres-container
    image: postgres
    env_file:
      - .env.prod
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5435:${DB_PORT}"
    volumes:
      - .postgres:/var/lib/postgres/data
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # Добавляем инициализационный скрипт
    restart: always